visibility: private
name: Update ICS File


on:
  schedule:
    - cron: '*/2 * * * *' # Dieser Cron-Job läuft alle 5 Minuten
  workflow_dispatch: # Ermöglicht manuelles Auslösen

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ICS file
      run: |
        curl -o Sonnenstube.ics https://outlook.office365.com/owa/calendar/4518a988d0944fca94f5b205f98cdcd0@stiftung-maihof.ch/510748a0c1de4e839b4289ac36d974177704059246271755894/calendar.ics
        curl -o Sunset.ics https://outlook.office365.com/owa/calendar/4287428fd7f544c7bca16df6dfb1ac96@stiftung-maihof.ch/be7d9df655e84117bedd640daf726d8c14969555720922775328/calendar.ics
        curl -o Cafeteria.ics https://outlook.office365.com/owa/calendar/b5ed77a50f4542c59bbb81751889d370@stiftung-maihof.ch/1473d21d1e784a3888dd7cd536b005e616889489424505442350/calendar.ics
        curl -o Saal.ics https://outlook.office365.com/owa/calendar/b56a89587f2540e5a11bbb36096d86a3@stiftung-maihof.ch/bf589cadc85c47febf66be7d1aa387ac13102600388834368974/calendar.ics
        curl -o Sonnhalde-Stuebli.ics https://outlook.office365.com/owa/calendar/d7268c93af504350be1de1c00bc3cad3@stiftung-maihof.ch/1a1c02dc3a134ae28c0fff6f50cd0a7b16897505493309632908/calendar.ics
        curl -o Sitzungszimmer-Dienste.ics https://outlook.office365.com/owa/calendar/044eb8fe8865429984f5a1430bc58feb@stiftung-maihof.ch/52e7f4a47e344ef1b5eb1609f5826a8f8473981965959299703/calendar.ics
        

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Sonnenstube.ics
        git add Sunset.ics
        git add Cafeteria.ics
        git add Saal.ics
        git add Sonnhalde-Stuebli.ics
        git add Sitzungszimmer-Dienste.ics
        git commit -m "Update ICS file - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}
