name: Update ICS File


on:
  schedule:
    - cron: '*/5 * * * *' # Dieser Cron-Job läuft alle 5 Minuten
  workflow_dispatch: # Ermöglicht manuelles Auslösen

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ICS file
      run: |
        curl -o Sonnenstube.ics ${{ secrets.Sonnenstube }}
        curl -o Sunset.ics ${{ secrets.SUNSET }}
        curl -o Cafeteria.ics ${{ secrets.CAFETERIA }}
        curl -o Saal.ics ${{ secrets.SAAL }}
        curl -o Sonnhalde-Stuebli.ics ${{ secrets.SONNHALDESTUEBLI }}
        curl -o Sitzungszimmer-Dienste.ics ${{ secrets.SITZUNGSZIMMERDIENSTE }}
        curl -o SiZi-Geschaeftstelle-3OG.ics ${{ secrets.SIZIGESCHAEFTSTELLE3OG }}
        curl -o SiZi3OG-Gang.ics ${{ secrets.SIZI3OGGANG }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Sonnenstube.ics
        git add Sunset.ics
        git add Cafeteria.ics
        git add Saal.ics
        git add Sonnhalde-Stuebli.ics
        git add Sitzungszimmer-Dienste.ics
        git add SiZi-Geschaeftstelle-3OG.ics
        git add SiZi3OG-Gang.ics

        
        git commit -m "Update ICS file - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
